In [1]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12],
               [13, 14, 15, 16]])

In [2]:
# 최소값, 최대값

print(np.min(arr), np.max(arr))

1 16


In [3]:
# 최소값, 최대값 인덱스

print(np.argmin(arr), np.argmax(arr))

0 15


In [4]:
# 전체 합, 평균

print(np.sum(arr), np.mean(arr))

136 8.5


In [5]:
# 특정 값 인덱스

np.where(arr == 5)

(array([1], dtype=int64), array([0], dtype=int64))

In [6]:
# 1차원 -> 2차원 변환

arr1 = np.arange(10)
print(arr1)

arr2 = arr1.reshape(2, 5)
print(arr2)
np.shape(arr2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


(2, 5)

In [7]:
arr2 = arr1.reshape(2, -1)     # 마지막에 -1을 작성하면 자동으로 알맞은 형태로 변환됨
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
# 2차원 -> 1차원 변환

arr1 = arr2.reshape(1, -1)
arr1

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [9]:
# 1차원 정렬

arr = np.array([10, 2, 3, 4, 6, 5, 7, 8, 1, 9])
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.sort(arr)[::-1]      # -1을 추가하면 내림차순으로 바뀜(기본옵션은 오름차순)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [11]:
# n차원 정렬

arr = np.array([[11, 9, 11, 12],
               [8, 9, 5, 7],
               [3, 1, 2, 4],
               [14, 16, 13, 15]])

In [12]:
# 행방향 정렬(오름차순)

print(np.sort(arr, axis = 0))

[[ 3  1  2  4]
 [ 8  9  5  7]
 [11  9 11 12]
 [14 16 13 15]]


In [13]:
# 행방향 정렬(내림차순)

print(np.sort(arr, axis = 0)[::-1])

[[14 16 13 15]
 [11  9 11 12]
 [ 8  9  5  7]
 [ 3  1  2  4]]


In [14]:
# 열방향 정렬

np.sort(arr, axis = 1)

array([[ 9, 11, 11, 12],
       [ 5,  7,  8,  9],
       [ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [15]:
np.sort(arr, axis = 1)[::-1]

array([[13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  7,  8,  9],
       [ 9, 11, 11, 12]])

In [16]:
# 정렬된 행렬의 원본 행렬 인덱스 반환 - 오름차순
# np.argsort()

arr = np.array([3, 1, 9, 5])

np.argsort(arr)

array([1, 0, 3, 2], dtype=int64)

In [17]:
# 정렬된 행렬의 원본 행렬 인덱스 반환 - 내림차순
# np.argsort()[::-1]

arr = np.array([3, 1, 9, 5])

np.argsort(arr)[::-1]

array([2, 3, 0, 1], dtype=int64)

In [18]:
# np.argsort() 사용 예

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

print(np.argsort(score_array))     # score를 오름차순 정렬 했을 때의 원본 인덱스
print(name_array[np.argsort(score_array)])     # score 오름차순으로 name_array의 이름 출력

[0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [22]:
# 행렬

arr1 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
arr2 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

In [23]:
# 행렬의 곱셈(내적 연산)

np.dot(arr1, arr2)

array([[ 90, 100, 110, 120],
       [202, 228, 254, 280],
       [314, 356, 398, 440],
       [426, 484, 542, 600]])

In [24]:
# 행렬 집계 함수: np.sum, np.max, np.min, np.mean, np.std

arr = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12],
               [13, 14, 15, 16]])

In [25]:
# 전체 합계

np.sum(arr)

136

In [26]:
# 행방향 합계

np.sum(arr, axis = 0)

array([28, 32, 36, 40])

In [27]:
# 열방향 합계

np.sum(arr, axis = 1)

array([10, 26, 42, 58])

In [19]:
# 전치행렬
# np.transpose()

arr = np.array([[1, 2],
               [3, 4]])

print(arr)

print(np.transpose(arr))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
