In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import selenium

- 배열(array): 같은 타입을 가지는 데이터가 나열된 집합. 같은 데이터 타입으로 이루어짐
- numpy: 다차원 배열을 쉽고 효율적으로 계산할 수 있도록 해주는 파이썬의 대표 라이브러리
- 배열 생성 방법
    1. 리스트 자료형에서 numpy로 변환
    2. numpy 자체 생성 함수 활용
    3. 파일 기반 배열 생성

In [4]:
# 리스트 자료형에서 numpy 변환

mylist = [[1, 2, 3], [4, 5, 6]]
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# numpy 자체 생성 함수 활용

np.array([1, 2, 3], dtype = int)

array([1, 2, 3])

In [9]:
# 자체 생성 함수

# 1배열
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [10]:
# 0배열
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [11]:
# 단위 행렬
np.eye(2, 2)

array([[1., 0.],
       [0., 1.]])

In [12]:
# 사용자 지정 값
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

In [13]:
# 랜덤 값
np.random.rand(2, 2)

array([[0.65060115, 0.3488779 ],
       [0.07178776, 0.66454593]])

In [14]:
# 등간격 배열 생성

np.arange(2, 10, 2)     # np.arange(a, b, c): a부터 b-1까지의 수를 c간격으로

array([2, 4, 6, 8])

In [16]:
np.linspace(1, 10, 5)     # np.linspace(a, b, c): a부터 b까지의 수를 균등한 간격으로 c개

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [17]:
# 간격을 지정해서 슬라이싱

arr = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12],
               [13, 14, 15, 16]])

arr[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [18]:
# 2, 3행 슬라이싱

arr[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
# 2, 3열 슬라이싱

arr[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [20]:
# 1, 3행 인덱싱

arr[[0, 2], :]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [21]:
# 1, 2열 인덱싱

arr[:, [0, 1]]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [23]:
# 1, 2행, 1, 2열 인덱싱(겹치는 부분)

arr[[0, 1], [0, 1]]

array([1, 6])